---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r echo=TRUE}
#unzip file
unzip('activity.zip',overwrite = F) #unzip activity file
data<-read.csv(file = 'activity.csv') #load data
library(lubridate)
#convert to date
data$date<-ymd(data$date)
```

## What is mean total number of steps taken per day?
```{r echo=TRUE}
library(dplyr)
#aggregation for total steps per day
sData<- data %>% filter(!is.na(steps)) %>% group_by(date) %>% select(steps) %>% summarise(totalSteps=sum(steps))
#plots
library(ggplot2)
ggplot(data=sData, aes(totalSteps))+geom_histogram(binwidth = 500)+ 
  xlab("total steps")+ylab("frequency")+
  ggtitle("total number of steps taken each day")

#mean and median
print(paste0("mean: ",mean(sData$totalSteps)))
print(paste0("median: ",median(sData$totalSteps)))
  
```


## What is the average daily activity pattern?
```{r echo=TRUE}
#average per interval
avgData<- data %>% group_by(interval) %>% select(steps) %>% summarise(avgSteps=mean(steps, na.rm=T))

#max
mx<-max(avgData$avgSteps,na.rm = T)
#interval of max
i<-avgData[avgData$avgSteps==mx,1][[1]]

print(paste0("maximum: ",mx))
print(paste0("interval of maximum: ",i))

#plot
ggplot(data=avgData, aes(interval,avgSteps))+geom_line()+ 
  xlab("intervals")+ylab("average")+
  ggtitle("average daily activity")+geom_vline(aes(xintercept=i), color="red")

```


## Imputing missing values
```{r echo=TRUE}
#na statistic
nna<-length(data[is.na(data$steps),1])
print(paste0("number of NA values: ",nna))

newData<-data

avgData<-data.frame(avgData) #convert from tbl_df
#finds indexes of NA steps 
ind<-which(is.na(newData$steps))
#replace na values with averages
newData[ind,"steps"]<-sapply(newData[ind,"interval"],
      function(x) 
      {
        avgData[x==avgData$interval,"avgSteps"]
      }
)

#aggregation for total steps per day
sData<- newData %>% group_by(date) %>% select(steps) %>% summarise(totalSteps=sum(steps))
ggplot(data=sData, aes(totalSteps))+geom_histogram(binwidth = 500)+ 
  xlab("total steps")+ylab("frequency")+
  ggtitle("total number of steps taken each day")

print(paste0("mean: ",mean(sData$totalSteps)))
print(paste0("median: ",median(sData$totalSteps)))
```

As you can see median is different to median from first step
The histogram after changing missing values is different around median

## Are there differences in activity patterns between weekdays and weekends?
```{r echo=TRUE}
dataWeekdays<-newData
#finds weekdays and weekend
dataWeekdays$weekend<-factor(ifelse(weekdays(dataWeekdays$date) %in% c("Saturday", "Sunday"),"weekend","weekday"))

#averages per interval and weekday/weekend
avgWeekdaysData<- dataWeekdays %>% group_by(interval, weekend) %>% select(steps) %>% summarise(avgSteps=mean(steps))

#plot
ggplot(data=avgWeekdaysData)+geom_line(aes(interval,avgSteps))+facet_grid(weekend~.)+
xlab("interval")+ylab("average steps")+
  ggtitle("weekday and weekend average steps")
```
